### PR TITLE
Implemented add product feature

### PR DESCRIPTION
**Pull request by EdmundTangg**

### CODE REVIEW

**Comment by EdmundTangg** [comment]
Fix #9

**Comment by leongxingyu** [comment]
LGTM

**Comment by cheeseong2001** [comment]
No problems on my side!

**Comment by wjunjie01** [comment]
It looks fine!

**Comment by Kobot7** [comment]
Fixed the merge conflict, all looks fine

**Comment by NgYaoDong** [comment]
Looking good!

**Pull request merged**
